// This file is generated by a script.

#ifndef _WS2812_PIND_HEADER_H_INCLUDED

#define _WS2812_PIND_HEADER_H_INCLUDED

void neopixel_show_long_P1_4(uint32_t dataAndLen);

#define neopixel_show_P1_4(ADDR, LEN)                                          \
  neopixel_show_long_P1_4((((uint16_t)(ADDR)) & 0xFFFF) |                      \
                          (((uint32_t)(LEN)&0xFF) << 16));

void neopixel_show_long_P1_5(uint32_t dataAndLen);

#define neopixel_show_P1_5(ADDR, LEN)                                          \
  neopixel_show_long_P1_5((((uint16_t)(ADDR)) & 0xFFFF) |                      \
                          (((uint32_t)(LEN)&0xFF) << 16));

#endif
